---
- name: NFS
  hosts: all
  become: true
  vars:
    directorio: "/var/nfs_shared"
    opciones: "192.168.1.30/24(rw,sync,root_squash)"
    permisos: '0777'
    
  tasks:
  
    - name: instalacion de NFS y actualizacion
      ansible.builtin.dnf:
        name:
          - nfs-utils
        state: latest


    - name: creacion de directorio NFS o probar que existe
      ansible.builtin.file:
        path: "{{ directorio }}"
        state: directory
        mode: "{{ permisos }}"
        owner: nobody
        group: nobody


    - name: compartir en /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        state: present
        line: '{{ directorio }} {{ permisos }}'
      notify: reinicio NFS server


    - name: compartir export
      ansible.builtin.command: "exportfs -rav"


    - name: permitir en firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - nfs
        - mountd


  handlers:
    - name: reinicio NFS server
      ansible.builtin.service:
        name: nfs-server
        state: restarted
        enabled: true
...
