---
- name: Install and configure Fail2Ban
  hosts: hardening
  become: yes

  vars:
    fail2ban_jail:
      sshd:
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 3
        bantime: 3600

  tasks:
    - name: Install Fail2Ban
      package:
        name: fail2ban
        state: present

    - name: Create jail.local configuration
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart fail2ban

    - name: Ensure fail2ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes

  handlers:
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
